In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.ndim # Один ранг, или одномерная матрица

1

In [5]:
a.shape

(3,)

In [6]:
a.size

3

In [10]:
b = np.array([[4, 5, 6], [7, 8, 9]])
b

array([[4, 5, 6],
       [7, 8, 9]])

In [11]:
b.size

6

In [12]:
b.ndim # 2 измерения

2

In [13]:
b.shape # 2 строки и 3 столбца

(2, 3)

In [14]:
a.dtype

dtype('int32')

In [15]:
a.dtype.name

'int32'

In [16]:
a.itemsize

4

In [17]:
b.itemsize

4

In [20]:
b.dtype = np.int32 # Назначение типа переменным в массиве

In [21]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
b = np.arange(15, 115, 5).reshape(4, 5)
b

array([[ 15,  20,  25,  30,  35],
       [ 40,  45,  50,  55,  60],
       [ 65,  70,  75,  80,  85],
       [ 90,  95, 100, 105, 110]])

In [25]:
a.ndim
b.ndim

2

In [26]:
a = np.arange(0, 4, 0.5) # Можно делать с дробным шагом
a

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

In [27]:
a = np.linspace(11, 60) # По умолчанию делает 50 элементов, если нет 3 параметра
a

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.,
       24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36.,
       37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.,
       50., 51., 52., 53., 54., 55., 56., 57., 58., 59., 60.])

In [28]:
a.dtype

dtype('float64')

In [29]:
a.reshape(5, 10) # Чтобы сделать array в матрицу

array([[11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.],
       [31., 32., 33., 34., 35., 36., 37., 38., 39., 40.],
       [41., 42., 43., 44., 45., 46., 47., 48., 49., 50.],
       [51., 52., 53., 54., 55., 56., 57., 58., 59., 60.]])

In [30]:
np.linspace(0, 4, 15) # 15 элементов от 0 до 4

array([0.        , 0.28571429, 0.57142857, 0.85714286, 1.14285714,
       1.42857143, 1.71428571, 2.        , 2.28571429, 2.57142857,
       2.85714286, 3.14285714, 3.42857143, 3.71428571, 4.        ])

In [31]:
np.linspace(0.5, 7.5, 9)

array([0.5  , 1.375, 2.25 , 3.125, 4.   , 4.875, 5.75 , 6.625, 7.5  ])

In [32]:
print(repr(a))

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.,
       24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36.,
       37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.,
       50., 51., 52., 53., 54., 55., 56., 57., 58., 59., 60.])


In [33]:
print(a)

[11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28.
 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46.
 47. 48. 49. 50. 51. 52. 53. 54. 55. 56. 57. 58. 59. 60.]


In [34]:
str(a)

'[11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28.\n 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46.\n 47. 48. 49. 50. 51. 52. 53. 54. 55. 56. 57. 58. 59. 60.]'

In [35]:
a = np.arange(10)
b = np.arange(10, 20)

In [46]:
SIZE = 10
res = np.zeros((SIZE))

In [47]:
res

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
res = np.zeros((SIZE), dtype=np.int_)

In [49]:
res.dtype

dtype('int32')

In [43]:
# Если сложение делать в питоне
for i in range(SIZE):
    res[i] = a[i] + b[i]
res

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [44]:
a + b # В numpy

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [45]:
a * b

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [50]:
SHAPE = 2, 3
SHAPE

(2, 3)

In [51]:
a = np.arange(1, 7).reshape(SHAPE)
b = np.arange(9, 15).reshape(SHAPE)

In [53]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
b

array([[ 9, 10, 11],
       [12, 13, 14]])

In [54]:
a * b

array([[ 9, 20, 33],
       [48, 65, 84]])

In [56]:
b - a

array([[8, 8, 8],
       [8, 8, 8]])

In [57]:
np.diff(a) # Разница соседних элементов 2 - 1, 3 - 2, 5-4, 6-5 поэтому 2х2 матрица

array([[1, 1],
       [1, 1]])

In [58]:
a * 2 # Скалярное произведение, каждое умножилось на 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [60]:
np.sum(a) # Сумма всех элементов

21

In [61]:
a.sum()

21

In [62]:
a.ndim

2

In [63]:
np.sum(a, axis=0) # Сложили по столбцу

array([5, 7, 9])

In [64]:
a.sum(axis=1) # Сложили по строке

array([ 6, 15])

In [65]:
np.prod(a) # Перемножить все элементы

720

In [66]:
np.prod(a, axis=0)

array([ 4, 10, 18])

In [67]:
a.prod(axis=1)

array([  6, 120])

In [68]:
a2 = a ** 2
a2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [69]:
np.sqrt(a2) # Корень из всех элементов

array([[1., 2., 3.],
       [4., 5., 6.]])

In [70]:
a < 4

array([[ True,  True,  True],
       [False, False, False]])

In [71]:
a >= 5

array([[False, False, False],
       [False,  True,  True]])

In [72]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [73]:
a[2]

8

In [74]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [75]:
a[3:9:2]

array([ 27, 125, 343], dtype=int32)

In [76]:
a[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [79]:
a[:9:3] = 111 # Замена среза значением 111
a

array([111,   1,   8, 111,  64, 125, 111, 343, 512, 729], dtype=int32)

In [81]:
SHAPE = 5, 4

In [82]:
b = np.arange(20).reshape(SHAPE)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [84]:
def f(x, y):
    return 10 * x + y

In [85]:
f(3, 4)

34

In [86]:
np.fromfunction(f, SHAPE) # По функции сделали матрицу

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.],
       [30., 31., 32., 33.],
       [40., 41., 42., 43.]])

In [88]:
b = np.fromfunction(f, SHAPE, dtype=int) # По функции сделали матрицу
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [89]:
b[2]

array([20, 21, 22, 23])

In [90]:
b[2][3]

23

In [91]:
b[2, 3]

23

In [92]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [93]:
b[:, 3]

array([ 3, 13, 23, 33, 43])

In [94]:
b[2, :]

array([20, 21, 22, 23])

In [95]:
SHAPE_3D = (2, 3, 4)

In [97]:
c = np.arange(24).reshape(SHAPE_3D) # Получается 2 матрицы, 3 строки, 4 столбца
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [98]:
c.ndim

3

In [99]:
c.shape

(2, 3, 4)

In [100]:
c[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [101]:
c[1, 2]

array([20, 21, 22, 23])

In [102]:
c[1, 2, 3]

23

In [103]:
c[:, :, 3]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [104]:
... # Элепсис заменяет доветоия с запятой

Ellipsis

In [105]:
c[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
c[..., 2] # Пример использования элипсиса

array([[ 2,  6, 10],
       [14, 18, 22]])

In [108]:
c + 4

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27]]])

In [110]:
c ** 2 # Происходит операция со всеми элементами

array([[[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]],

       [[144, 169, 196, 225],
        [256, 289, 324, 361],
        [400, 441, 484, 529]]], dtype=int32)

In [111]:
SHAPE_5D = tuple(i for i in range(2, 7))
SHAPE_5D

(2, 3, 4, 5, 6)

In [112]:
d = np.empty(SHAPE_5D, dtype=np.int16)
d

array([[[[[-22176,   9197,    429,      0,  21552,   8173],
          [   429,      0,  26224,   8277,    429,      0],
          [ -3280,   8279,    429,      0,  18096,   8253],
          [   429,      0,  26224,   8277,    429,      0],
          [  2224,   8195,    429,      0, -10256,   8333]],

         [[   429,      0,  15856,   8276,    429,      0],
          [ 15920,   8276,    429,      0, -23696,   8253],
          [   429,      0, -23120,   8253,    429,      0],
          [-28432,   8333,    429,      0,  -1616,   8196],
          [   429,      0,  -1616,   8196,    429,      0]],

         [[  7152,   8253,    429,      0,  -1616,   8196],
          [   429,      0,  18160,   8335,    429,      0],
          [-20368,   8307,    429,      0,  -5776,   8332],
          [   429,      0,   2224,   8195,    429,      0],
          [ 30064,   8196,    429,      0, -31184,   8304]],

         [[   429,      0,  -5136,   8282,    429,      0],
          [ 18224,   8253,    429,

In [125]:
np.empty([2, 2])

array([[0., 1.],
       [2., 3.]])

In [126]:
d[1, :, :, :, 5]

array([[[ 8253,     0,  8276,     0,  8253],
        [    0,  8304,     0,  8304,     0],
        [ 8253,     0,  8304,     0,  8304],
        [    0,  8253,     0,  8276,     0]],

       [[ 8304,     0,  8253,     0,  8253],
        [    0,  8253,     0,  8304,     0],
        [ 8196,     0,  8194,     0,  9379],
        [    0,  9379,     0,  9379,     0]],

       [[ 9379,     0,  9379,     0,  9379],
        [    0,  9379,     0, 10240,     0],
        [ 9379,     0,  8251,     0,  9379],
        [    0,  9379,     0,  9379,     0]]], dtype=int16)

In [127]:
d.shape

(2, 3, 4, 5, 6)

In [128]:
d1 = d[1, :, :, :, 4]
d1

array([[[  7152,    429,  15920,    429,  17968],
        [   429, -31184,    429, -31184,    429],
        [  5296,    429, -31184,    429, -31184],
        [   429, -23120,    429,  15856,    429]],

       [[-31184,    429,  17968,    429,   7152],
        [   429,   5296,    429, -31184,    429],
        [ -1616,    429, -18064,    429,  14576],
        [   429,  17792,    429,  17952,    429]],

       [[ 18192,    429,  18432,    429,  20912],
        [   429,  18832,    429,     40,    429],
        [ 18912,    429,  -7440,    429,   7088],
        [   429,   7152,    429,   7280,    429]]], dtype=int16)

In [129]:
d1.shape

(3, 4, 5)

In [133]:
d2 = d1[1, ..., 2]
d2

array([ 17968,    429, -18064,    429], dtype=int16)

In [134]:
d2.shape

(4,)

In [135]:
d[..., 3]

array([[[[   0, 8277,    0, 8277,    0],
         [8276,    0, 8253,    0, 8196],
         [   0, 8335,    0, 8195,    0],
         [8282,    0, 8253,    0, 8253]],

        [[   0, 8282,    0, 8282,    0],
         [8253,    0, 8304,    0, 8196],
         [   0, 8196,    0, 8253,    0],
         [8253,    0, 8253,    0, 8304]],

        [[   0, 8253,    0, 8195,    0],
         [8253,    0, 8253,    0, 8304],
         [   0, 8276,    0, 8253,    0],
         [8253,    0, 8253,    0, 8304]]],


       [[[   0, 8253,    0, 8304,    0],
         [8253,    0, 8253,    0, 8276],
         [   0, 8253,    0, 8253,    0],
         [8253,    0, 8304,    0, 8250]],

        [[   0, 8276,    0, 8250,    0],
         [8194,    0, 8253,    0, 8276],
         [   0, 8276,    0, 9379,    0],
         [9379,    0, 9379,    0, 9379]],

        [[   0, 9379,    0, 9379,    0],
         [9379,    0, 9379,    0, 9255],
         [   0, 9376,    0, 8251,    0],
         [9377,    0, 9379,    0, 9379]]]], d

In [136]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [137]:
for elem in c:
    print()
    print(elem)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [140]:
# Если делаем перебор всех занчений в питоне
for elemx in c:
    for elemy in elemx:
        for elemz in elemy:
            print(elemz, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 

In [142]:
# Тот же результат, но без вложенных циклов
for elem in c.flat:
    print(elem, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 

In [157]:
# Получаетcя это генератор
elems = c.flat
elems

In [158]:
next(elems)

0

In [159]:
next(elems)

1

In [160]:
# Развернули в одну длинную строчку
elems = c.ravel()
elems

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [161]:
print(type(elems))

<class 'numpy.ndarray'>


In [162]:
elems.dtype

dtype('int32')

In [164]:
elems.ndim

1

In [165]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [166]:
c.reshape(2, 12) # соблюдены условия 2х3х4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [167]:
c.reshape(12, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [168]:
c.reshape(4, 3, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [171]:
c.T # Транспонирование

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [174]:
x = np.arange(1, 13).reshape(4, 3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [175]:
x.shape

(4, 3)

In [177]:
v = np.array([1, 0 ,1])
v

array([1, 0, 1])

In [178]:
x.shape

(4, 3)

In [179]:
v.shape

(3,)

In [180]:
# Хотим привести v к той же форме, что и x
vv = np.tile(v, (4, 1))
vv

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [181]:
vv.shape

(4, 3)

In [182]:
x + vv

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [183]:
print(x + v)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [184]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [188]:
# Такойже размерностью как и Б
c = np.zeros_like(b)
c

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [189]:
c[2] = range(1, 5)
c[3] = range(7, 3, -1)
c

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 2, 3, 4],
       [7, 6, 5, 4],
       [0, 0, 0, 0]])

In [192]:
# Добавили снизу, как uinion
vs = np.vstack((b, c))
vs

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 1,  2,  3,  4],
       [ 7,  6,  5,  4],
       [ 0,  0,  0,  0]])

In [195]:
# Добавили сбоку как join
hs = np.hstack((b, c))
hs

array([[ 0,  1,  2,  3,  0,  0,  0,  0],
       [10, 11, 12, 13,  0,  0,  0,  0],
       [20, 21, 22, 23,  1,  2,  3,  4],
       [30, 31, 32, 33,  7,  6,  5,  4],
       [40, 41, 42, 43,  0,  0,  0,  0]])

In [196]:
# Тоже самое что и np.hstack
np.column_stack((b, c))

array([[ 0,  1,  2,  3,  0,  0,  0,  0],
       [10, 11, 12, 13,  0,  0,  0,  0],
       [20, 21, 22, 23,  1,  2,  3,  4],
       [30, 31, 32, 33,  7,  6,  5,  4],
       [40, 41, 42, 43,  0,  0,  0,  0]])

In [197]:
np.column_stack((b, c)) == np.hstack((b, c))

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [198]:
np.all(np.column_stack((b, c)) == np.hstack((b, c)))

True

In [200]:
a1 = np.arange(1, 3)
a2 = np.arange(5, 7)
print(a1, a2)

[1 2] [5 6]


In [203]:
np.hstack((a1, a2))


array([1, 2, 5, 6])

In [202]:
np.vstack((a1, a2))

array([[1, 2],
       [5, 6]])

In [204]:
# Уже не похоже, что было раньше с column_stack, получилось первая строка первые эелементы
np.column_stack((a1, a2))

array([[1, 5],
       [2, 6]])

In [206]:
a1[:, np.newaxis]

array([[1],
       [2]])

In [208]:
np.column_stack((a1[:, np.newaxis], a2[:, np.newaxis]))

array([[1, 5],
       [2, 6]])

In [211]:
np.hstack((a1[:, np.newaxis], a2[:, np.newaxis]))

array([[1, 5],
       [2, 6]])

In [212]:
np.row_stack((a1, a2))

array([[1, 2],
       [5, 6]])

In [213]:
a

array([111,   1,   8, 111,  64, 125, 111, 343, 512, 729], dtype=int32)

In [214]:
np.hsplit(a, 2) # Разделение массива

[array([111,   1,   8, 111,  64], dtype=int32),
 array([125, 111, 343, 512, 729], dtype=int32)]

In [215]:
np.hsplit(a, 5)

[array([111,   1], dtype=int32),
 array([  8, 111], dtype=int32),
 array([ 64, 125], dtype=int32),
 array([111, 343], dtype=int32),
 array([512, 729], dtype=int32)]

In [217]:
c = np.arange(12).reshape(4, 3)
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [218]:
np.vsplit(c, 2)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [219]:
d = np.arange(8, 20)
d

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [220]:
d.size

12

In [222]:
c.size

12

In [223]:
d.shape # Видно, что в D и в C одинаковое количетсво элементов, значит можно прировнять

(12,)

In [224]:
c.shape

(4, 3)

In [225]:
# Массив D стал двухмерным
d.shape = c.shape

In [227]:
d

array([[ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [228]:
b = d >= 13
b

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [229]:
# Получили элементы где True
print(d[b])

[13 14 15 16 17 18 19]


In [230]:
d[b] = 42

In [231]:
d

array([[ 8,  9, 10],
       [11, 12, 42],
       [42, 42, 42],
       [42, 42, 42]])

In [235]:
palette = np.array([
    [0, 0 , 0],
    [255, 0, 0],
    [0, 255, 0],
    [0, 0, 255],
    [255, 255, 255]
])
palette

array([[  0,   0,   0],
       [255,   0,   0],
       [  0, 255,   0],
       [  0,   0, 255],
       [255, 255, 255]])

In [236]:
image = np.array([
    [0, 1, 2, 0],
    [0, 3, 4, 0]
])
image

array([[0, 1, 2, 0],
       [0, 3, 4, 0]])

In [237]:
print(palette[image])

[[[  0   0   0]
  [255   0   0]
  [  0 255   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0 255]
  [255 255 255]
  [  0   0   0]]]


In [238]:
a = np.arange(2, 6)
b = np.array([8, 5, 3])
c = np.array([5, 4, 6, 8, 7])
print(a, b, c)

[2 3 4 5] [8 5 3] [5 4 6 8 7]


In [239]:
ax, bx, cx = np.ix_(a, b, c)
print(ax, bx, cx)

[[[2]]

 [[3]]

 [[4]]

 [[5]]] [[[8]
  [5]
  [3]]] [[[5 4 6 8 7]]]


In [240]:
ax

array([[[2]],

       [[3]],

       [[4]],

       [[5]]])

In [241]:
bx

array([[[8],
        [5],
        [3]]])

In [244]:
cx

array([[[5, 4, 6, 8, 7]]])

In [245]:
result = ax + bx * cx
result

array([[[42, 34, 50, 66, 58],
        [27, 22, 32, 42, 37],
        [17, 14, 20, 26, 23]],

       [[43, 35, 51, 67, 59],
        [28, 23, 33, 43, 38],
        [18, 15, 21, 27, 24]],

       [[44, 36, 52, 68, 60],
        [29, 24, 34, 44, 39],
        [19, 16, 22, 28, 25]],

       [[45, 37, 53, 69, 61],
        [30, 25, 35, 45, 40],
        [20, 17, 23, 29, 26]]])

In [246]:
a[3] + b[2] * c[4]

26

In [247]:
result[3, 2, 4]

26

In [249]:
a = np.arange(40)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [250]:
# -1 это неизветный элемент, нампи сам сделает форму из 4 и 5 и подделает -1
a.shape = 4, -1, 5

In [251]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])